// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className }>
//         {/* <style>{`
//           body::-webkit-scrollbar {
//             display: none;
//           }
//           .hide-scrollbar::-webkit-scrollbar {
//             display: none;
//           }
//         `}</style> */}
//         <Navbar />
//         {children}
//         <footer className="pt-10">Footer</footer>
//       </body>
//     </html>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can include your metadata here */}
      </head>
      <body className={inter.className + ' bg-gray-800'}>
        <Navbar />
        {children}
        <footer className="pt-10">Footer</footer>
      </body>
    </html>
  );
}
